--- #YAML:1.0
name:               Audio-TagLib
version:            1.57
abstract:           Library for reading and editing audio meta data
author:
    - Dongxu, Ma <dongxu@cpan.org>
    - Geoffrey Leach <gleach@cpan.org>
license: perl_5 - The Perl 5 License (Artistic 1 & GPL 1)
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
          xs
          sample
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
